// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");
require("chromedriver");

describe("StandardMarketCryptoSelectorTest", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("StandardMarketCryptoTest", async function () {
    await driver.get("https://finance.yahoo.com/quote/TSLA/");
    {
      const elements = await driver.findElements(By.css(".Fz\\(36px\\)"));
      assert(elements.length);
    }
  });
});
